server:
  port: 9000
spring:
  application:
    name: cf-mysql-java-broker
  datasource:
    url: jdbc:mysql://localhost/test
    username: root
    password: =P0o9i8u7 
    driverClassName: com.mysql.jdbc.Driver
  main:
    show_banner: false
