# Default values for mysql-java-broker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: mysql-java-broker
  tag: latest
  pullPolicy: Always
service:
  name: mysql-java-broker
  type: ClusterIP
  externalPort: 80
  internalPort: 9000